services:
  - type: web
    name: avatar-ai-bot
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bot:app --bind 0.0.0.0:$PORT --workers 1 --threads 8"